(defun areaCuadrado ()
  (princ "Dame la medida de uno de los lados del cuadrado:  ")
  (setq num1 (read))
  (* num1 num1)
)

(defun areaTrianguloEQ ()
  (princ "Dame la altura del triangulo:  ")
  (setq num1 (read))
  (princ "Dame la base del triangulo:  ")
  (setq num2 (read))
  (/ (* num1 num2) 2)
)